# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptRecData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rollno', models.CharField(default='', max_length=15)),
                ('mobileno', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypt.CryptRecData')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
