# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0002_auto_20160629_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/crypt/%Y/%m/%d'),
        ),
    ]
