# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0004_auto_20160706_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptrecdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
