# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0019_auto_20160710_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptrecdata',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
