# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0025_auto_20160819_0206'),
        ('crypt', '0023_auto_20160815_1231'),
    ]

    operations = [
    ]
