# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0007_auto_20160815_1231'),
        ('charge', '0009_auto_20160818_2302'),
    ]

    operations = [
    ]
