# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.URLField(),
        ),
    ]
