# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrecdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
