# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:05
from __future__ import unicode_literals

import clutch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutch', '0006_auto_20160710_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=clutch.models.content_file_name),
        ),
    ]
